# Dependencies
# markdown:         redcarpet
# highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            DisFact
tagline:          ''
description:      Samarth Bansal's blog
url:              www.disfact.in
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

gem: [jekyll-paginate, jekyll-gists]

excerpt_separator: "<!--break-->"

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap